# Homework 2: BERT on AWS

In this homework, we will apply the BERT algorithm on Amazon Web Services.

This DataRec repository contains a pointer to accessing recommendation system data, installable via

`pip install datarec-lib`

### Task 1: Download the MovieLens 1m dataset. You should output a copy of the dataset on an AWS S3 bucket.

First, I set up aws CLI and ran `aws configure sso` with the Northwestern start URL and `us-east-2`.
aws s3 ls --profile mse-tl-dataeng300-EMR-549787090008

In [1]:
# aws sso login --profile mse-tl-dataeng300-EMR-549787090008
import os
import boto3
import pandas as pd

os.environ["AWS_SHARED_CREDENTIALS_FILE"] = "./.aws/credentials"
session = boto3.Session(
    profile_name="mse-tl-dataeng300-EMR-549787090008",
    region_name="us-east-2"
    )

In [2]:
s3 = session.client("s3")
response = s3.list_buckets()
if response['ResponseMetadata']['HTTPStatusCode'] == 200:
    print(response['Buckets'])

[{'Name': 'acharya-cui-sokolenko-mwaa', 'CreationDate': datetime.datetime(2026, 5, 1, 11, 48, 44, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::acharya-cui-sokolenko-mwaa'}, {'Name': 'acharya-de300-wi26', 'CreationDate': datetime.datetime(2026, 4, 29, 6, 17, 22, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::acharya-de300-wi26'}, {'Name': 'adams-agrawal-evensen-mwaa', 'CreationDate': datetime.datetime(2026, 4, 30, 23, 48, 34, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::adams-agrawal-evensen-mwaa'}, {'Name': 'ads-de300winter-airflow', 'CreationDate': datetime.datetime(2026, 4, 24, 22, 0, 35, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::ads-de300winter-airflow'}, {'Name': 'airflow-group6', 'CreationDate': datetime.datetime(2026, 4, 28, 22, 35, 13, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::airflow-group6'}, {'Name': 'airflowgroup5', 'CreationDate': datetime.datetime(2026, 5, 1, 7, 35, 34, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::airflowgroup5'}, {'Name': 'amde300', 'CreationDate': datetime.datetime(2026, 4, 27, 3, 16, 9, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::amde300'}, {'Name': 'andrewawsbucket', 'CreationDate': datetime.datetime(2026, 4, 29, 8, 55, 26, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::andrewawsbucket'}, {'Name': 'atmadja-benjamin-dong-mwaa', 'CreationDate': datetime.datetime(2026, 5, 1, 9, 54, 12, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::atmadja-benjamin-dong-mwaa'}, {'Name': 'atmadja-benson-mcgillis-wu-bucket', 'CreationDate': datetime.datetime(2026, 4, 29, 16, 32, 11, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::atmadja-benson-mcgillis-wu-bucket'}, {'Name': 'aws-logs-549787090008-us-east-1', 'CreationDate': datetime.datetime(2026, 4, 28, 18, 55, 34, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::aws-logs-549787090008-us-east-1'}, {'Name': 'aws-logs-549787090008-us-east-2', 'CreationDate': datetime.datetime(2026, 4, 29, 4, 19, 57, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::aws-logs-549787090008-us-east-2'}, {'Name': 'aws-sam-cli-managed-default-samclisourcebucket-fmrcacmtwnqj', 'CreationDate': datetime.datetime(2026, 4, 29, 11, 16, 30, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::aws-sam-cli-managed-default-samclisourcebucket-fmrcacmtwnqj'}, {'Name': 'aws-sam-cli-managed-default-samclisourcebucket-gkgousezsx38', 'CreationDate': datetime.datetime(2026, 4, 29, 4, 4, 21, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::aws-sam-cli-managed-default-samclisourcebucket-gkgousezsx38'}, {'Name': 'aws-sam-cli-managed-default-samclisourcebucket-jasccrluxmti', 'CreationDate': datetime.datetime(2026, 4, 27, 23, 39, 42, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::aws-sam-cli-managed-default-samclisourcebucket-jasccrluxmti'}, {'Name': 'aws-sam-cli-managed-default-samclisourcebucket-u1dyc2xcx9dr', 'CreationDate': datetime.datetime(2026, 4, 22, 21, 15, 14, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::aws-sam-cli-managed-default-samclisourcebucket-u1dyc2xcx9dr'}, {'Name': 'barnett-evan-lab3', 'CreationDate': datetime.datetime(2026, 4, 30, 21, 18, 9, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::barnett-evan-lab3'}, {'Name': 'beam-gutstein-bucket', 'CreationDate': datetime.datetime(2026, 5, 1, 9, 38, 51, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::beam-gutstein-bucket'}, {'Name': 'benjamin-bucket-lab8', 'CreationDate': datetime.datetime(2026, 4, 29, 2, 13, 32, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::benjamin-bucket-lab8'}, {'Name': 'benson-gillespie-liu-mwaa', 'CreationDate': datetime.datetime(2026, 4, 29, 14, 14, 38, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::benson-gillespie-liu-mwaa'}, {'Name': 'bhh-26spring', 'CreationDate': datetime.datetime(2026, 4, 21, 21, 16, 38, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::bhh-26spring'}, {'Name': 'brennanbensonawsbucket', 'CreationDate': datetime.datetime(2026, 4, 29, 0, 41, 50, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::brennanbensonawsbucket'}, {'Name': 'bustrust', 'CreationDate': datetime.datetime(2026, 5, 1, 7, 23, 34, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::bustrust'}, {'Name': 'carl-w-spring2026', 'CreationDate': datetime.datetime(2026, 4, 21, 21, 16, 36, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::carl-w-spring2026'}, {'Name': 'chen-gutstein-tenesaca-swarup-bucket', 'CreationDate': datetime.datetime(2026, 5, 1, 17, 19, 45, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::chen-gutstein-tenesaca-swarup-bucket'}, {'Name': 'chen-thampeera-wong-kim-swarup-bucket', 'CreationDate': datetime.datetime(2026, 4, 29, 23, 46, 47, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::chen-thampeera-wong-kim-swarup-bucket'}, {'Name': 'data-eng300-hw2-visuthikosol', 'CreationDate': datetime.datetime(2026, 5, 2, 22, 41, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::data-eng300-hw2-visuthikosol'}, {'Name': 'dde300-east1', 'CreationDate': datetime.datetime(2026, 5, 1, 11, 37, 44, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dde300-east1'}, {'Name': 'de300-1-mwaa', 'CreationDate': datetime.datetime(2026, 5, 1, 13, 33, 6, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-1-mwaa'}, {'Name': 'de300-aimeechooi-airflow', 'CreationDate': datetime.datetime(2026, 4, 28, 20, 28, 6, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-aimeechooi-airflow'}, {'Name': 'de300-airflow-cindy', 'CreationDate': datetime.datetime(2026, 4, 28, 23, 14, 28, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-airflow-cindy'}, {'Name': 'de300-airflow-output', 'CreationDate': datetime.datetime(2026, 4, 29, 7, 39, 19, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-airflow-output'}, {'Name': 'de300-airflow-rachel', 'CreationDate': datetime.datetime(2026, 4, 28, 23, 40, 34, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-airflow-rachel'}, {'Name': 'de300-airflow-tests', 'CreationDate': datetime.datetime(2026, 4, 28, 18, 16, 7, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-airflow-tests'}, {'Name': 'de300-amandakosmen-airflow', 'CreationDate': datetime.datetime(2026, 4, 28, 17, 52, 14, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-amandakosmen-airflow'}, {'Name': 'de300-aws-tutorial', 'CreationDate': datetime.datetime(2026, 4, 29, 9, 17, 33, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-aws-tutorial'}, {'Name': 'de300-benwrather-airflow2', 'CreationDate': datetime.datetime(2026, 4, 28, 18, 0, 52, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-benwrather-airflow2'}, {'Name': 'de300-bzl-wi2026', 'CreationDate': datetime.datetime(2026, 5, 1, 13, 30, 18, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-bzl-wi2026'}, {'Name': 'de300-demo-bucket', 'CreationDate': datetime.datetime(2026, 4, 28, 17, 15, 2, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-demo-bucket'}, {'Name': 'de300-garrettlee-airflow', 'CreationDate': datetime.datetime(2026, 5, 1, 9, 24, 54, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-garrettlee-airflow'}, {'Name': 'de300-group', 'CreationDate': datetime.datetime(2026, 4, 29, 5, 17, 9, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group'}, {'Name': 'de300-group-17-heartdata', 'CreationDate': datetime.datetime(2026, 4, 29, 7, 10, 50, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group-17-heartdata'}, {'Name': 'de300-group-17-mwaa', 'CreationDate': datetime.datetime(2026, 4, 29, 1, 40, 9, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group-17-mwaa'}, {'Name': 'de300-group1', 'CreationDate': datetime.datetime(2026, 4, 29, 3, 4, 17, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group1'}, {'Name': 'de300-group1-mwaa-output', 'CreationDate': datetime.datetime(2026, 4, 29, 4, 50, 27, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group1-mwaa-output'}, {'Name': 'de300-group11-mwaa', 'CreationDate': datetime.datetime(2026, 5, 1, 16, 37, 29, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group11-mwaa'}, {'Name': 'de300-group11-mwaa-output', 'CreationDate': datetime.datetime(2026, 4, 28, 20, 17, 41, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group11-mwaa-output'}, {'Name': 'de300-group13-airflow', 'CreationDate': datetime.datetime(2026, 4, 28, 18, 50, 54, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group13-airflow'}, {'Name': 'de300-group13-airflow-output', 'CreationDate': datetime.datetime(2026, 4, 29, 8, 20, 37, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group13-airflow-output'}, {'Name': 'de300-group2', 'CreationDate': datetime.datetime(2026, 4, 28, 22, 42, 30, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group2'}, {'Name': 'de300-group7-airflow-output', 'CreationDate': datetime.datetime(2026, 4, 28, 23, 56, 39, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group7-airflow-output'}, {'Name': 'de300-group7-module3', 'CreationDate': datetime.datetime(2026, 5, 1, 13, 57, 40, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group7-module3'}, {'Name': 'de300-group7-mwaa', 'CreationDate': datetime.datetime(2026, 4, 29, 8, 29, 3, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group7-mwaa'}, {'Name': 'de300-group8-airflow-output', 'CreationDate': datetime.datetime(2026, 4, 29, 3, 37, 30, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group8-airflow-output'}, {'Name': 'de300-group8-mwaa', 'CreationDate': datetime.datetime(2026, 4, 29, 9, 16, 5, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group8-mwaa'}, {'Name': 'de300-group8-project2', 'CreationDate': datetime.datetime(2026, 4, 28, 20, 57, 58, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-group8-project2'}, {'Name': 'de300-heart-disease-test', 'CreationDate': datetime.datetime(2026, 4, 28, 18, 2, 37, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-heart-disease-test'}, {'Name': 'de300-isaacwinoto-airflow', 'CreationDate': datetime.datetime(2026, 4, 29, 6, 55, 50, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-isaacwinoto-airflow'}, {'Name': 'de300-jasonlu-airflow', 'CreationDate': datetime.datetime(2026, 4, 29, 5, 52, 49, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-jasonlu-airflow'}, {'Name': 'de300-ktv-mwaa', 'CreationDate': datetime.datetime(2026, 4, 30, 16, 24, 13, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-ktv-mwaa'}, {'Name': 'de300-lily-bucket', 'CreationDate': datetime.datetime(2026, 4, 28, 22, 37, 54, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-lily-bucket'}, {'Name': 'de300-marcobenavides-airflow', 'CreationDate': datetime.datetime(2026, 4, 28, 23, 5, 42, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-marcobenavides-airflow'}, {'Name': 'de300-markzhang-airflow', 'CreationDate': datetime.datetime(2026, 4, 29, 5, 5, 29, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-markzhang-airflow'}, {'Name': 'de300-mikang-airflow', 'CreationDate': datetime.datetime(2026, 4, 29, 6, 51, 37, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mikang-airflow'}, {'Name': 'de300-mwaa', 'CreationDate': datetime.datetime(2026, 4, 28, 23, 31, 6, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mwaa'}, {'Name': 'de300-mwaa-19', 'CreationDate': datetime.datetime(2026, 4, 28, 21, 4, 35, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mwaa-19'}, {'Name': 'de300-mwaa-cal', 'CreationDate': datetime.datetime(2026, 4, 22, 18, 19, 55, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mwaa-cal'}, {'Name': 'de300-mwaa-ohmies', 'CreationDate': datetime.datetime(2026, 4, 30, 22, 55, 36, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mwaa-ohmies'}, {'Name': 'de300-mwaa-oregon', 'CreationDate': datetime.datetime(2026, 4, 27, 5, 1, 27, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mwaa-oregon'}, {'Name': 'de300-mwaa-output', 'CreationDate': datetime.datetime(2026, 4, 28, 20, 32, 47, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-mwaa-output'}, {'Name': 'de300-nataliehill-airflow', 'CreationDate': datetime.datetime(2026, 4, 28, 22, 34, 49, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-nataliehill-airflow'}, {'Name': 'de300-p3-g2', 'CreationDate': datetime.datetime(2026, 4, 28, 21, 53, 22, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-p3-g2'}, {'Name': 'de300-phoebekim-airflow', 'CreationDate': datetime.datetime(2026, 4, 29, 5, 54, 22, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-phoebekim-airflow'}, {'Name': 'de300-project-19', 'CreationDate': datetime.datetime(2026, 4, 28, 18, 31, 55, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project-19'}, {'Name': 'de300-project-group17', 'CreationDate': datetime.datetime(2026, 4, 30, 4, 2, 3, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project-group17'}, {'Name': 'de300-project3-group20', 'CreationDate': datetime.datetime(2026, 4, 28, 23, 46, 49, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project3-group20'}, {'Name': 'de300-project3-group20-output', 'CreationDate': datetime.datetime(2026, 4, 29, 0, 6, 44, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project3-group20-output'}, {'Name': 'de300-project4', 'CreationDate': datetime.datetime(2026, 4, 28, 20, 28, 37, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project4'}, {'Name': 'de300-project4-mwaa', 'CreationDate': datetime.datetime(2026, 4, 29, 3, 34, 2, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project4-mwaa'}, {'Name': 'de300-project4-mwaa-output', 'CreationDate': datetime.datetime(2026, 4, 28, 18, 2, 11, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-project4-mwaa-output'}, {'Name': 'de300-riadsouza-airflow', 'CreationDate': datetime.datetime(2026, 4, 29, 2, 56, 23, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-riadsouza-airflow'}, {'Name': 'de300-rodneyreichert-airflow', 'CreationDate': datetime.datetime(2026, 4, 28, 19, 50, 18, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-rodneyreichert-airflow'}, {'Name': 'de300-sebphemister-airflow', 'CreationDate': datetime.datetime(2026, 5, 1, 17, 35, 21, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-sebphemister-airflow'}, {'Name': 'de300-shreyasridhar-airflow', 'CreationDate': datetime.datetime(2026, 4, 29, 1, 43, 9, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-shreyasridhar-airflow'}, {'Name': 'de300-wakiuruwachiuri-airflow', 'CreationDate': datetime.datetime(2026, 4, 30, 7, 5, 39, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-wakiuruwachiuri-airflow'}, {'Name': 'de300-wilks', 'CreationDate': datetime.datetime(2026, 4, 29, 4, 15, 27, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-wilks'}, {'Name': 'de300-wn2024', 'CreationDate': datetime.datetime(2026, 4, 29, 6, 29, 19, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-wn2024'}, {'Name': 'de300-wn2024-airflow', 'CreationDate': datetime.datetime(2026, 4, 28, 23, 3, 22, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-wn2024-airflow'}, {'Name': 'de300-ziadelbadry', 'CreationDate': datetime.datetime(2026, 4, 29, 7, 38, 2, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300-ziadelbadry'}, {'Name': 'de300group13', 'CreationDate': datetime.datetime(2026, 4, 29, 8, 51, 5, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300group13'}, {'Name': 'de300spring2025', 'CreationDate': datetime.datetime(2026, 4, 29, 8, 22, 19, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300spring2025'}, {'Name': 'de300winter-airflow', 'CreationDate': datetime.datetime(2026, 4, 24, 16, 45, 33, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300winter-airflow'}, {'Name': 'de300winter2025', 'CreationDate': datetime.datetime(2026, 4, 29, 8, 18, 10, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::de300winter2025'}, {'Name': 'decherrie-winter26', 'CreationDate': datetime.datetime(2026, 4, 29, 15, 6, 54, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::decherrie-winter26'}, {'Name': 'desmond-hw4-airflow', 'CreationDate': datetime.datetime(2026, 4, 27, 14, 11, 16, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::desmond-hw4-airflow'}, {'Name': 'desmond-mwaa-lab8', 'CreationDate': datetime.datetime(2026, 4, 25, 3, 50, 8, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::desmond-mwaa-lab8'}, {'Name': 'desmondlab8', 'CreationDate': datetime.datetime(2026, 4, 28, 1, 36, 20, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::desmondlab8'}, {'Name': 'desmondnebahspark', 'CreationDate': datetime.datetime(2026, 5, 1, 8, 47, 39, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::desmondnebahspark'}, {'Name': 'dinglin-spring26', 'CreationDate': datetime.datetime(2026, 4, 28, 16, 23, 13, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dinglin-spring26'}, {'Name': 'dinglin-winter26', 'CreationDate': datetime.datetime(2026, 4, 28, 18, 38, 4, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dinglin-winter26'}, {'Name': 'don-bucket-lab8', 'CreationDate': datetime.datetime(2026, 4, 27, 3, 12, 16, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::don-bucket-lab8'}, {'Name': 'dongjdu8459-bucket', 'CreationDate': datetime.datetime(2026, 4, 29, 14, 1, 3, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dongjdu8459-bucket'}, {'Name': 'dongjoo-26spring', 'CreationDate': datetime.datetime(2026, 4, 21, 21, 16, 45, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dongjoo-26spring'}, {'Name': 'dse300-rheashah-airflow', 'CreationDate': datetime.datetime(2026, 5, 1, 8, 11, 15, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dse300-rheashah-airflow'}, {'Name': 'dxk-mwaa', 'CreationDate': datetime.datetime(2026, 4, 29, 2, 59, 45, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::dxk-mwaa'}, {'Name': 'elasticbeanstalk-us-east-2-549787090008', 'CreationDate': datetime.datetime(2026, 4, 29, 0, 0, 8, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::elasticbeanstalk-us-east-2-549787090008'}, {'Name': 'eo-airflow-group16', 'CreationDate': datetime.datetime(2026, 4, 29, 21, 24, 6, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::eo-airflow-group16'}, {'Name': 'eobucket-group16', 'CreationDate': datetime.datetime(2026, 4, 28, 20, 6, 42, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::eobucket-group16'}, {'Name': 'evensen-bucket', 'CreationDate': datetime.datetime(2026, 4, 29, 11, 43, 17, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::evensen-bucket'}, {'Name': 'fingerson-lacombefarina-mwaa', 'CreationDate': datetime.datetime(2026, 4, 29, 11, 10, 38, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::fingerson-lacombefarina-mwaa'}, {'Name': 'fingerson-winter26', 'CreationDate': datetime.datetime(2026, 4, 30, 8, 55, 41, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::fingerson-winter26'}, {'Name': 'gillespie-tenesaca-adams', 'CreationDate': datetime.datetime(2026, 5, 1, 3, 52, 18, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::gillespie-tenesaca-adams'}, {'Name': 'group10-airflow', 'CreationDate': datetime.datetime(2026, 4, 29, 7, 20, 20, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group10-airflow'}, {'Name': 'group11-data', 'CreationDate': datetime.datetime(2026, 4, 29, 5, 6, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group11-data'}, {'Name': 'group14-mwaa', 'CreationDate': datetime.datetime(2026, 4, 29, 3, 42, 36, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group14-mwaa'}, {'Name': 'group14-project3', 'CreationDate': datetime.datetime(2026, 4, 29, 8, 30, 12, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group14-project3'}, {'Name': 'group14-wine', 'CreationDate': datetime.datetime(2026, 4, 29, 8, 23, 43, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group14-wine'}, {'Name': 'group15-de300', 'CreationDate': datetime.datetime(2026, 4, 28, 20, 40, 15, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group15-de300'}, {'Name': 'group15-module3', 'CreationDate': datetime.datetime(2026, 4, 29, 13, 54, 23, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group15-module3'}, {'Name': 'group19-mwaa-output', 'CreationDate': datetime.datetime(2026, 4, 29, 2, 55, 39, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group19-mwaa-output'}, {'Name': 'group20-de300', 'CreationDate': datetime.datetime(2026, 4, 29, 12, 1, 38, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group20-de300'}, {'Name': 'group5-heart', 'CreationDate': datetime.datetime(2026, 4, 29, 2, 47, 20, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group5-heart'}, {'Name': 'group6-air', 'CreationDate': datetime.datetime(2026, 4, 29, 6, 59, 48, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group6-air'}, {'Name': 'group6-data', 'CreationDate': datetime.datetime(2026, 4, 29, 2, 0, 29, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group6-data'}, {'Name': 'group6-log', 'CreationDate': datetime.datetime(2026, 4, 28, 22, 9, 1, tzinfo=tzutc()), 'BucketArn': 'arn:aws:s3:::group6-log'}, {'Name': 'gro

In [3]:
import os
import zipfile
import requests
import botocore

url = "https://files.grouplens.org/datasets/movielens/ml-1m.zip"
bucket_name = "bhh-26spring"
keys = ["movies.dat", "ratings.dat", "users.dat"]

zip_path = "ml-1m.zip"
extract_dir = ""


def file_exists_in_s3(s3, bucket, key):
    try:
        s3.head_object(Bucket=bucket, Key=key)
        return True
    except botocore.exceptions.ClientError as e:
        if e.response["Error"]["Code"] == "404":
            return False
        raise


def download_zip(url, zip_path):
    response = requests.get(url)
    response.raise_for_status()

    with open(zip_path, "wb") as f:
        f.write(response.content)


def unzip_file(zip_path, extract_dir):
    with zipfile.ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall(extract_dir)


# Download and unzip locally
if not os.path.exists(zip_path):
    print("downloading the zip file...")
    download_zip(url, zip_path)
else:
    print("Zip file exists on local already, skipping")

if not os.path.exists(os.path.join(extract_dir, "ml-1m")):
    print("unzipping file...")
    unzip_file(zip_path, extract_dir)
else:
    print("files alr unzipped locally, skipping.")

# Upload missing files
for key in keys:
    s3_key = key
    local_path = os.path.join(extract_dir, "ml-1m", key)

    if file_exists_in_s3(s3, bucket_name, s3_key):
        print(f"{s3_key} already exists in S3, skipping.")
    else:
        print(f"Uploading {s3_key}...")
        s3.upload_file(local_path, bucket_name, s3_key)
        print(f"Uploaded {s3_key} to S3!")

Zip file exists on local already, skipping
files alr unzipped locally, skipping.
movies.dat already exists in S3, skipping.
ratings.dat already exists in S3, skipping.
users.dat already exists in S3, skipping.

### Task 2. Using only movies that are released before the year 1980, inclusive. Create embeddings for the BERT algorithm. For the same set of items (movies) in the dataset, you should create the embeddings once and output a copy of the necessary intermediate results on the S3 bucket.

In [4]:
movies_path = "ml-1m/movies.dat"
ratings_path = "ml-1m/ratings.dat"
users_path = "ml-1m/users.dat"
movies = pd.read_csv(
    movies_path,
    sep="::",
    engine="python",
    encoding="latin-1",
    names=["movie_id", "title", "genres"]
)

ratings = pd.read_csv(
    ratings_path,
    sep="::",
    engine="python",
    encoding="latin-1",
    names=["user_id", "movie_id", "rating", "timestamp"]
)

users = pd.read_csv(
    users_path,
    sep="::",
    engine="python",
    encoding="latin-1",
    names=["user_id", "gender", "age", "occupation", "zip"]
)

In [5]:
import numpy as np
import torch
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModel
import faiss
import re

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
MODEL_NAME = "distilbert-base-uncased"  # for illustration, 66M model

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
encoder = AutoModel.from_pretrained(MODEL_NAME).to(DEVICE)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertModel LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |  |
------------------------+------------+--+-
vocab_transform.weight  | UNEXPECTED |  |
vocab_layer_norm.bias   | UNEXPECTED |  |
vocab_layer_norm.weight | UNEXPECTED |  |
vocab_projector.bias    | UNEXPECTED |  |
vocab_transform.bias    | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [6]:
def extract_year(title):
    match = re.search(r"\((\d{4})\)", title)
    return int(match.group(1)) if match else None


movies["year"] = movies["title"].apply(extract_year)

items = movies[
    movies["year"].notna() & (movies["year"] <= 1980)
].copy()

items["text"] = items["title"] + ". Genres: " + items["genres"].str.replace("|", ", ")

print(f"Movies selected: {len(items)}")

Movies selected: 887

In [ ]:
@torch.no_grad()
def bert_embed(texts, max_len=128, batch_size=32):
    all_embs = []

    for i in range(0, len(texts), batch_size): # batching loop
        chunk = texts[i:i+batch_size]

        batch = tokenizer(
            chunk,
            padding=True,
            truncation=True,
            max_length=max_len,
            return_tensors="pt"
        )
        batch = {k: v.to(DEVICE) for k, v in batch.items()}

        out = encoder(**batch)
        cls = out.last_hidden_state[:, 0]
        emb = F.normalize(cls, dim=-1)

        all_embs.append(emb.cpu().numpy().astype("float32"))

        del batch, out, cls, emb
        if DEVICE == "cuda":
            torch.cuda.empty_cache()

    return np.vstack(all_embs)


def embed_to_vec(items, batch_size=32):
    texts = items["text"].tolist()
    item_id_list = items["movie_id"].tolist()

    item_vecs = bert_embed(texts, batch_size=batch_size)

    index = faiss.IndexFlatIP(item_vecs.shape[1])
    index.add(item_vecs)

    return item_vecs, item_id_list, index


item_vecs, item_id_list, index = embed_to_vec(items)

In [8]:
output_dir = "offline_bert_outputs"
os.makedirs(output_dir, exist_ok=True)
metadata_path = os.path.join(output_dir, "movies_pre_1980_metadata.csv")
vecs_path = os.path.join(output_dir, "movies_pre_1980_bert_vectors.npy")
ids_path = os.path.join(output_dir, "movies_pre_1980_movie_ids.npy")
faiss_path = os.path.join(output_dir, "movies_pre_1980_faiss.index")

items[["movie_id", "title", "genres", "year", "text"]].to_csv(metadata_path, index=False)
# print(items[["movie_id", "title", "genres", "year", "text"]])
np.save(vecs_path, item_vecs)
np.save(ids_path, np.array(item_id_list))
faiss.write_index(index, faiss_path)

In [10]:
def upload_to_s3(local_path, bucket_name, s3_key):
    s3.upload_file(local_path, bucket_name, s3_key)
    print(f"Uploaded s3://{bucket_name}/{s3_key}")

s3_prefix = "movielens/offline_bert_outputs"
for local_path in [metadata_path, vecs_path, ids_path, faiss_path]:
    filename = os.path.basename(local_path)
    upload_to_s3(
        local_path,
        bucket_name,
        f"{s3_prefix}/{filename}"
    )

Uploaded s3://bhh-26spring/movielens/offline_bert_outputs/movies_pre_1980_metadata.csv
Uploaded s3://bhh-26spring/movielens/offline_bert_outputs/movies_pre_1980_bert_vectors.npy
Uploaded s3://bhh-26spring/movielens/offline_bert_outputs/movies_pre_1980_movie_ids.npy
Uploaded s3://bhh-26spring/movielens/offline_bert_outputs/movies_pre_1980_faiss.index

### 3. Recommend five movies for each of the following users. The recommendations should be saved in a file on the S3 bucket containing User_Type, Last_Interaction_Time, other user summaries in the dataset,and a list of recommended movies:

Cold user: a user that the system has no data on.
Top user: a random user who has frequently rated movies (number of interactions among the top 5% of users).

In [11]:
# helper mappings
id_to_idx = {mid: i for i, mid in enumerate(item_id_list)}
id_to_title = dict(zip(items["movie_id"], items["title"]))

In [12]:
def build_user_text(user_id, ratings_df, items_df, N=3):
    hist = (
        ratings_df[ratings_df["user_id"] == user_id]
        .sort_values("timestamp")
        .tail(N)["movie_id"]
        .tolist()
    )

    # only keep movies that exist in the candidate item set
    valid_ids = set(items_df["movie_id"])
    hist = [mid for mid in hist if mid in valid_ids]

    if not hist:
        return "no history", set()

    text = (
        items_df.set_index("movie_id")
        .loc[hist, "text"]
        .tolist()
    )

    return " ".join(text), set(hist)

In [13]:
def recommend(user_id, ratings_df, items_df, item_id_list, index, k=5, N=3):
    user_text, seen = build_user_text(user_id, ratings_df, items_df, N=N)
    u = bert_embed([user_text])
    search_k = min(k + len(seen) + 20, len(item_id_list))
    scores, idx = index.search(u, search_k)
    recs = []
    for score, j in zip(scores[0], idx[0]):
        if j == -1:
            continue

        mid = item_id_list[j]

        if mid in seen:
            continue

        row = items_df[items_df["movie_id"] == mid].iloc[0]

        recs.append({
            "movie_id": int(mid),
            "title": row["title"],
            "genres": row["genres"],
            "year": int(row["year"]) if "year" in row and pd.notna(row["year"]) else None,
            "score": float(score)
        })

        if len(recs) == k:
            break

    return recs

In [14]:
# top user
user_counts = ratings.groupby("user_id").size().reset_index(name="num_interactions")
threshold = user_counts["num_interactions"].quantile(0.95)

top_users = user_counts[user_counts["num_interactions"] >= threshold]
top_user_id = top_users.sample(1, random_state=42)["user_id"].iloc[0]

top_pre_recs = recommend(
    user_id=top_user_id,
    ratings_df=ratings,
    items_df=items,
    item_id_list=item_id_list,
    index=index,
    k=5,
    N=3
)

In [15]:
# cold user
ratings_pre = ratings[ratings["movie_id"].isin(item_id_list)]

movie_stats = (
    ratings_pre
    .groupby("movie_id")
    .agg(
        rating_count=("rating", "count"),
        avg_rating=("rating", "mean")
    )
    .reset_index()
)

movie_stats["score"] = movie_stats["avg_rating"] * np.log1p(movie_stats["rating_count"])

cold_pre_recs = (
    movie_stats
    .sort_values("score", ascending=False)
    .head(5)
    .merge(items[["movie_id", "title", "genres", "year"]], on="movie_id")
    .to_dict(orient="records")
)

In [16]:
top_user_events = ratings[ratings["user_id"] == top_user_id]
top_user_info = users[users["user_id"] == top_user_id].iloc[0]

last_time_pre = pd.to_datetime(
    top_user_events["timestamp"].max(),
    unit="s"
).isoformat()

pre_1980_results = [
    {
        "Dataset": "pre_1980",
        "User_Type": "Cold user",
        "Last_Interaction_Time": None,
        "User_Summary": "No interaction history available. Recommendations use popular highly-rated pre-1980 movies.",
        "Recommended_Movies": cold_pre_recs
    },
    {
        "Dataset": "pre_1980",
        "User_Type": "Top user",
        "Last_Interaction_Time": last_time_pre,
        "User_Summary": {
            "user_id": int(top_user_id),
            "num_interactions": int(len(top_user_events)),
            "avg_rating": float(top_user_events["rating"].mean()),
            "gender": top_user_info["gender"],
            "age": int(top_user_info["age"]),
            "occupation": int(top_user_info["occupation"]),
            "zip": str(top_user_info["zip"])
        },
        "Recommended_Movies": top_pre_recs
    }
]

In [17]:
user_ratings = ratings[ratings["user_id"] == top_user_id]
user_pre = user_ratings[user_ratings["movie_id"].isin(item_id_list)]

liked = user_pre[user_pre["rating"] >= 4]

if len(liked) == 0:
    liked = user_pre  # fallback

liked_vecs = np.array([
    item_vecs[id_to_idx[mid]]
    for mid in liked["movie_id"]
    if mid in id_to_idx
])

user_vec = liked_vecs.mean(axis=0)
user_vec = user_vec / np.linalg.norm(user_vec)

In [18]:
cold = pre_1980_results[0]

print("User Type:", cold["User_Type"])
print("Last Interaction:", cold["Last_Interaction_Time"])
print("Summary:", cold["User_Summary"])

User Type: Cold user
Last Interaction: None
Summary: No interaction history available. Recommendations use popular highly-rated pre-1980 movies.

In [18]:
top = pre_1980_results[1]

print("User Type:", top["User_Type"])
print("Last Interaction:", top["Last_Interaction_Time"])
print("Summary:")
for k, v in top["User_Summary"].items():
    print(f"  {k}: {v}")

User Type: Top user
Last Interaction: 2003-02-15T22:38:13
Summary:
  user_id: 3519
  num_interactions: 666
  avg_rating: 3.045045045045045
  gender: F
  age: 25
  occupation: 14
  zip: 11215

In [19]:
top_user_events = ratings[ratings["user_id"] == top_user_id]

top_user_history = top_user_events.merge(
    movies[["movie_id", "title", "genres"]],
    on="movie_id",
    how="left"
)

top_user_history.head()

,user_id,movie_id,rating,timestamp,title,genres
0,3519,2987,3,968340999,Who Framed Roger Rabbit? (1988),Adventure|Animation|Film-Noir
1,3519,3791,3,969996802,Footloose (1984),Drama
2,3519,3793,4,976889941,X-Men (2000),Action|Sci-Fi
3,3519,2991,3,971201646,Live and Let Die (1973),Action
4,3519,2054,1,968340601,"Honey, I Shrunk the Kids (1989)",Adventure|Children's|Comedy|Fantasy|Sci-Fi

In [20]:
print("Cold user recs:")
for m in pre_1980_results[0]["Recommended_Movies"]:
    print(m["title"])

print("\nTop user recs:")
for m in pre_1980_results[1]["Recommended_Movies"]:
    print(m["title"])

Cold user recs:
Star Wars: Episode IV - A New Hope (1977)
Godfather, The (1972)
Star Wars: Episode V - The Empire Strikes Back (1980)
Casablanca (1942)
One Flew Over the Cuckoo's Nest (1975)

Top user recs:
All the King's Men (1949)
Long Goodbye, The (1973)
To Sir with Love (1967)
Candidate, The (1972)
Buddy Holly Story, The (1978)

### 4. Repeat steps 2 and 3 but with the full set of data. You should be able to reuse your work from earlier.

In [21]:
full_items = movies.copy()

full_items["text"] = (
    full_items["title"]
    + ". Genres: "
    + full_items["genres"].str.replace("|", ", ", regex=False)
)

full_item_vecs = bert_embed(full_items["text"].tolist())

full_item_id_list = full_items["movie_id"].tolist()

full_index = faiss.IndexFlatIP(full_item_vecs.shape[1])
full_index.add(full_item_vecs)

### 5. Choose and rate 10 movies and create a “user profile” for yourself. Save your user profile on the S3 bucket. Recommend 5 movies for yourself and save the results on the S3 bucket.

In [22]:
# check if not taken user id
users[users["user_id"] == 999999]

Empty DataFrame
Columns: [user_id, gender, age, occupation, zip]
Index: []

In [23]:
def movie_lookup(text):
    print(movies[movies["title"].str.contains(text, case=False, na=False)])

searches = ["Shawshank Redemption", "Toy Story", "Fight Club", "Star Wars", "Avengers"]
for search in searches:
    print("\nSearch for:", search)
    movie_lookup(search)

Search for: Shawshank Redemption
     movie_id                             title genres  year
315       318  Shawshank Redemption, The (1994)  Drama  1994

Search for: Toy Story
      movie_id               title                       genres  year
0            1    Toy Story (1995)  Animation|Children's|Comedy  1995
3045      3114  Toy Story 2 (1999)  Animation|Children's|Comedy  1999

Search for: Fight Club
      movie_id              title genres  year
2890      2959  Fight Club (1999)  Drama  1999

Search for: Star Wars
      movie_id                                              title  \
257        260          Star Wars: Episode IV - A New Hope (1977)
1178      1196  Star Wars: Episode V - The Empire Strikes Back...
1192      1210  Star Wars: Episode VI - Return of the Jedi (1983)
2559      2628   Star Wars: Episode I - The Phantom Menace (1999)

                                   genres  year
257       Action|Adventure|Fantasy|Sci-Fi  1977
1178    Action|Adventure|Drama|Sci-Fi|War  1980
1192  Action|Adventure|Romance|Sci-Fi|War  1983
2559      Action|Adventure|Fantasy|Sci-Fi  1999

Search for: Avengers
      movie_id                 title            genres  year
2084      2153  Avengers, The (1998)  Action|Adventure  1998

In [24]:
my_user_id = 999999

my_ratings = pd.DataFrame([
    {"user_id": my_user_id, "movie_id": 1, "rating": 5, "timestamp": pd.Timestamp.now().timestamp()},     # Toy Story
    {"user_id": my_user_id, "movie_id": 260, "rating": 5, "timestamp": pd.Timestamp.now().timestamp()},   # Star Wars
    {"user_id": my_user_id, "movie_id": 1196, "rating": 5, "timestamp": pd.Timestamp.now().timestamp()},  # Empire Strikes Back
    {"user_id": my_user_id, "movie_id": 318, "rating": 5, "timestamp": pd.Timestamp.now().timestamp()},   # Shawshank Redemption
    {"user_id": my_user_id, "movie_id": 1270, "rating": 4, "timestamp": pd.Timestamp.now().timestamp()},  # Back to the Future
    {"user_id": my_user_id, "movie_id": 1210, "rating": 4, "timestamp": pd.Timestamp.now().timestamp()},  # Return of the Jedi
    {"user_id": my_user_id, "movie_id": 2571, "rating": 5, "timestamp": pd.Timestamp.now().timestamp()},  # Matrix
    {"user_id": my_user_id, "movie_id": 2959, "rating": 4, "timestamp": pd.Timestamp.now().timestamp()},  # Fight Club
    {"user_id": my_user_id, "movie_id": 2153, "rating": 5, "timestamp": pd.Timestamp.now().timestamp()},  # The Avengers
    {"user_id": my_user_id, "movie_id": 3114, "rating": 4, "timestamp": pd.Timestamp.now().timestamp()},  # Toy Story 2
])

In [25]:
ratings_with_me = pd.concat([ratings, my_ratings], ignore_index=True)

my_recs = recommend(
    user_id=my_user_id,
    ratings_df=ratings_with_me,
    items_df=full_items,
    item_id_list=full_item_id_list,
    index=full_index,
    k=5,
    N=10
)

my_recs

[{'movie_id': 2628,
  'title': 'Star Wars: Episode I - The Phantom Menace (1999)',
  'genres': 'Action|Adventure|Fantasy|Sci-Fi',
  'year': 1999,
  'score': 0.9702330231666565},
 {'movie_id': 1544,
  'title': 'Lost World: Jurassic Park, The (1997)',
  'genres': 'Action|Adventure|Sci-Fi|Thriller',
  'year': 1997,
  'score': 0.9688523411750793},
 {'movie_id': 329,
  'title': 'Star Trek: Generations (1994)',
  'genres': 'Action|Adventure|Sci-Fi',
  'year': 1994,
  'score': 0.9676699042320251},
 {'movie_id': 1205,
  'title': 'Transformers: The Movie, The (1986)',
  'genres': "Action|Animation|Children's|Sci-Fi|Thriller|War",
  'year': 1986,
  'score': 0.967428982257843},
 {'movie_id': 1371,
  'title': 'Star Trek: The Motion Picture (1979)',
  'genres': 'Action|Adventure|Sci-Fi',
  'year': 1979,
  'score': 0.9665452241897583}]

In [26]:
my_profile = my_ratings.merge(
    movies[["movie_id", "title", "genres"]],
    on="movie_id",
    how="left"
)

my_profile_path = "my_user_profile.csv"
my_profile.to_csv(my_profile_path, index=False)

s3.upload_file(
    my_profile_path,
    bucket_name,
    "movielens/my_user_profile/my_user_profile.csv"
)

print("uploaded my user profile to S3")

uploaded my user profile to S3

In [27]:
my_results = {
    "User_Type": "Self user profile",
    "User_ID": my_user_id,
    "Last_Interaction_Time": pd.to_datetime(
        my_ratings["timestamp"].max(),
        unit="s"
    ).isoformat(),
    "User_Summary": {
        "num_interactions": len(my_ratings),
        "avg_rating": float(my_ratings["rating"].mean()),
        "profile_description": "Self-created user profile based on 10 manually rated movies."
    },
    "Rated_Movies": my_profile.to_dict(orient="records"),
    "Recommended_Movies": my_recs
}

In [28]:
import json
my_results_path = "my_recommendations.json"

with open(my_results_path, "w") as f:
    json.dump(my_results, f, indent=2)

s3.upload_file(
    my_results_path,
    bucket_name,
    "movielens/my_user_profile/my_recommendations.json"
)

print("uploaded my recommendations to S3")

uploaded my recommendations to S3